import { RefundStatus } from '../enums';
import { RefundFailureReason } from '../enums/RefundFailureReason';

/**
 * Refund status response
 *
 * @export
 * @interface RefundStatusResponse
 */
export interface RefundStatusResponse {
    /**
     * Unique ID of a refund generated by Paynow
     *
     * @type {string}
     * @memberof RefundStatusResponse
     */
    refundId: string;

    /**
     * Current status of the refund
     *
     * @type {RefundStatus}
     * @memberof RefundStatus
     */
    status: RefundStatus;

    /**
     * Reason if status is `FAIL`
     *
     * @type {RefundFailureReason}
     * @memberof RefundStatusResponse
     */
    failureReason?: RefundFailureReason;
}
